title: Muhammad aziz
email: mhdaziz629@gmail.com
description: I am a passionate and dedicated student majoring in Informatics Engineering at the State Polytechnic of Lhokseumawe. I have a strong interest in Information Technology, especially in programming, software development, and understanding how systems work. I enjoy learning new technologies, solving problems through code, and continuously improving my skills. My goal is to become a reliable IT professional who can contribute to innovative projects and help create efficient digital solutions.
url: "https://mhmmd-aziz.github.io/"
plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag



